title: UCI Anime Community Club
remote_theme: "murraco/jekyll-theme-minimal-resume"
description: Anime Club at UCI
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jeepracer98.github.io/uci.moe/" # the base hostname & protocol for your site